let config = {};
config.secret = "xxxxxxxxxxxxxxxxxxxxxxxxxxx"; //CHANGE THIS!!!! CHANGE THIS!!!!
config.coreURL = "https://edenprairie_students.na.rapidbiz.com/php/scl/edenprairie/index.php";
config.maxRequests = 2000; //Max requests per 5min.
config.key = "etc/ssl/testing_localhost.key"; //CHANGE THIS!!!! CHANGE THIS!!!!
config.cert = "etc/ssl/testing_localhost.crt"; //CHANGE THIS!!!! CHANGE THIS!!!!
config.sslPort = 8443;
config.port = 8080;
module.exports = config;
